# Site settings
title: Vincent's Blog
email: vincent.waisun@gmail.com
description: My simple blog.
baseurl: "/vincent_blog"
twitter_username: 
avatar: "http://vincentcheungwaisun.appspot.com/img/resume_profile.png" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Vincent Cheung" # Set default author name
      categories: "General"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
